baseURL = "http://crkmythical.github.io"  # The URL of your site.
title = "Mr.Frame"     # Title of your site
theme = "zdoc"

#defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

copyright = "&copy;{year} Mr.Frame, All Rights Reserved"
timeout = 1000000
enableEmoji = true
paginate = 13  # 分页
rssLimit = 1000

googleAnalytics = ""

disableKinds = ["taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"
