[[main]]
  identifier = "devsecops"
  name = "DevSecOps"
  url = "devsecops"
  weight = 1

[[main]]
  identifier = "redTeam"
  name = "redTeam"
  url = "red"
  weight = 2

[[main]]
  identifier = "Blog"
  name = "Blog"
  url = "blog"
  weight = 3



