[[main]]
  identifier = "dso"
  name = "DevSecOps"   # navbar
  url = "dso"     # conten/<url>
  weight = 1     # position 

[[main]]
  identifier = "red"
  name = "redTeam"
  url = "red"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3



